// The return types from the controllers
// Types describe the action, what happened in your application. SLIDER_MOVED, BUTTON_CLICKED, USER_SELECTED etc..
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_REGISTER_SUCCESS = 'RESET_REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const TOGGLE_MFA_FAIL = 'TOGGLE_MFA_FAIL';
export const SET_MFA_FLAG = 'SET_MFA_FLAG';

export const LOGIN_SAVE = 'LOGIN_SAVE';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const REMOVE_LOGIN_LOADING = 'REMOVE_LOGIN_LOADING';
export const TOGGLE_MFA = 'TOGGLE_MFA';
export const SET_MFA_TOGGLE_LOADING ='SET_MFA_TOGGLE_LOADING';
export const REMOVE_MFA_TOGGLE_LOADING = 'REMOVE_MFA_TOGGLE_LOADING';
export const RESET_MFA_CHANGE_SUCCESS = 'RESET_MFA_CHANGE_SUCCESS';